name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 math_operations

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover tests

  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compress the project
        run: zip -r math_operations.zip math_operations

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: math_operations_artifact
          path: math_operations.zip

  deploy:
    name: Simulate Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate deployment
        run: echo "Deployment successful. Artifact ready." 
